# Generated by Django 5.0.6 on 2024-06-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='phone_user',
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
