# Generated by Django 5.0.6 on 2024-06-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_remove_userprofiles_phone_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='first_name',
        ),
    ]
