# Generated by Django 4.2.11 on 2024-06-06 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelService', '0003_hotel_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='details/')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='details/')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='details/')),
                ('image_four', models.ImageField(blank=True, null=True, upload_to='details/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelService.hotel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
