# Generated by Django 4.2.11 on 2024-06-06 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelService', '0004_detailhotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailhotel',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='HotelService.hotel'),
        ),
    ]
